### ISSUE TITLE
Readout Software described in README is Missing

### ISSUE THREAD

**Issue by travc** [Sensirion/shtc3_ble_beacon#2]
I'd love to see some code (python preferably) to receive the data on a Raspberry Pi as described in the Readme.

**Comment by abrauchli** [comment]
Hi @travc thanks for the report. Kindly note that the person in charge internally is currently out of office so it might take a few weeks.

@Fototux it's indeed described in the readme that there should be software, do we have anything we can hand out or should we fix the readme?

**Comment by travc** [comment]
I have a very small script using the pygatt which gets one-shot reads of temperature, humidity, and battery.  It is pretty slow, you have to supply the device address (no scanning), and I haven't bothered to figure out how to grab the logs off of the gadget... But it is something.
https://github.com/travc/pihvac/blob/master/smartgadgetBLEread.py

**Comment by ojousima** [comment]
It's been a while, but I'd love to see the software part :)

**Comment by Fototux** [comment]
Sorry for the late answer. I started this as a private project and didn't had the time to proceed so far. I just added the script I use for reading the BLE data to the the repo
https://github.com/Sensirion/shtc3_ble_beacon/tree/master/software
