### ISSUE TITLE
Firmware source code missing in the folder

### ISSUE THREAD

**Issue by kattaliraees** [Sensirion/shtc3_ble_beacon#3]
in the readme file, it's mentioned **'firmware (hex files and source code to program the microcontroller)'**. But inside the firmware folder, hex files only available and no source code for NRF52

**Comment by Fototux** [comment]
Sorry, I missed that the code is not in the repo. I will upload the code soon.

**Comment by kattaliraees** [comment]
Any luck with the firmware?

**Comment by Fototux** [comment]
Sorry for the long delay. The firmware source code is online now.

Nordic is updating the SDK way to often. The now uploaded version is working with the latest SDK v17.0.2. 
I managed now to implement the update of the beacon data without using specific SDK functions. So it should be less sensitive to changes of the SDK.
