### ISSUE TITLE
Updating old python beacon reader to modern bleak package - temperature encoding of the BLE characteristics ?

### ISSUE THREAD

**Issue by markdoerr** [Sensirion/shtc3_ble_beacon#4]
Hallo Sensiron Beacon developers,

for a student demonstration project, I tried to write an updated version of the Bluetooth readout of SHT31 beacon (blescan.py) with the modern python *bleak* package, since the original bluetooth python package is outdated:

```
import asyncio
from bleak import BleakClient

BLE_DEVICE_MAC_ADDRESS = "E4:A0:36:CA:7B:7E" # BLE_DEVICE_MAC_ADDRESS of the device (beacon)
TEMPERATURE_UUID = "00001234-b38d-4985-720e-0f993a68ee41"
TEMPERATURE_HANDLE = 49

def calculate_temperature(data):
    print("temp:", data, type(data))
    print("== temp - calc : ", (data / 65536.) * 175. - 45)

async def main(BLE_DEVICE_MAC_ADDRESS):
    async with BleakClient(BLE_DEVICE_MAC_ADDRESS) as client:

        services = client.services
                
        for service in services:
            for char in service.characteristics:
                print("--->", char.handle)
                if char.handle == TEMPERATURE_HANDLE : # TEMPERATURE_UUID : 
                    char_data = await client.read_gatt_char(char.uuid)
                    print("temperature raw:", char_data, type(char_data), len(char_data))

                    temp_data = int.from_bytes(char_data, byteorder='little') # which bytes contain the temperature value?

                    calculate_temperature(temp_data)

asyncio.run(main(BLE_DEVICE_MAC_ADDRESS))
```

But I am stuck with the line extracting temp_data, because it is not clear to me, what part of the 4 byte array returning as char_data does really contain the temperature information which could be then converted as described in the documentation to deg. celsius (with the above formula). Could you please help ? Thanks a lot in advance.

**Comment by LeonieFierz** [comment]
Hi @markdoerr 

You can see in the firmware implementation how the data is encoded. Refer to https://github.com/Sensirion/shtc3_ble_beacon/blob/master/firmware/main.c, advertising_update.
The first two byte 0 and 1 are temperature ticks (uint16), byte 2 and 3 humidity ticks (uint16) and the byteorder is big endian. So I suggest the following line of code (not tested):

 `temp_ticks = int.from_bytes(char_data[0,2], byteorder='big') `
